/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_batch2;
import demo_batch2.batch2_app;
import demo_batch2.pas1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Swetha
 */
public class res extends javax.swing.JFrame {
Connection con;
Statement st;
PreparedStatement ps2;
ResultSet rs;
    /**
     * Creates new form res
     */
    public res() {
        initComponents();
        try{
Class.forName("oracle.jdbc.OracleDriver");
JOptionPane.showMessageDialog(this,"Driver Loaded!");
try {
con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe",
        "swetha","swetha");
JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
}
catch (SQLException ex) {
Logger.getLogger(batch2_app.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}
}
catch(ClassNotFoundException ex){
Logger.getLogger(batch2_app.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sourceid = new javax.swing.JComboBox<>();
        destid = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        train_name = new javax.swing.JComboBox<>();
        setsource = new javax.swing.JTextField();
        setdest = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        class1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nop = new javax.swing.JTextField();
        pro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BOOKING");

        jLabel2.setText("FROM");

        jLabel3.setText("TO");

        sourceid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select station" }));
        sourceid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceidActionPerformed(evt);
            }
        });

        destid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select station" }));
        destid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destidActionPerformed(evt);
            }
        });

        jLabel4.setText("TRAIN");

        train_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select train" }));
        train_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                train_nameActionPerformed(evt);
            }
        });

        setsource.setText("jTextField1");
        setsource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setsourceActionPerformed(evt);
            }
        });

        setdest.setText("jTextField1");

        jLabel5.setText("CLASS");

        class1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select class" }));
        class1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class1ActionPerformed(evt);
            }
        });

        jLabel6.setText("DATE");

        dod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodActionPerformed(evt);
            }
        });

        jLabel7.setText("NO OF PASSENGERS");

        nop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopActionPerformed(evt);
            }
        });

        pro.setText("PROCEED");
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(164, 164, 164)
                                .addComponent(sourceid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(class1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(train_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(destid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dod, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(nop))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setdest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setsource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(pro)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sourceid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setsource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(destid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(setdest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(train_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(class1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pro)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sourceidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceidActionPerformed
        // TODO add your handling code here:
        String s1name= "select stationname from station";
        
        try
        {
            ps2=con.prepareStatement(s1name);
            System.out.println("before ps2");
            ResultSet rs=ps2.executeQuery();
            System.out.println("after ps2");
            
            while(rs.next()){
                String ss1name=rs.getString("stationname");
                sourceid.addItem(ss1name);
               System.out.println(ss1name);
                
            }
            String selectedsource=sourceid.getSelectedItem().toString();
            setsource.setText(selectedsource);

                
            }
         catch(SQLException e){
                 
                 }
    }//GEN-LAST:event_sourceidActionPerformed

    private void destidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destidActionPerformed
        // TODO add your handling code here:
        String s2name= "select stationname from station";
        
         try
        {
            ps2=con.prepareStatement(s2name);
            System.out.println("before ps2");
            ResultSet rs=ps2.executeQuery();
            System.out.println("after exec");
            
            while(rs.next()){
                String ss2name=rs.getString("stationname");
                destid.addItem(ss2name);
            }
            
            String selecteddest=destid.getSelectedItem().toString();
            System.out.println(selecteddest);
            setdest.setText(selecteddest);                
            }
         catch(SQLException e){
                 
                 }
    }//GEN-LAST:event_destidActionPerformed

    private void setsourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setsourceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_setsourceActionPerformed

    private void train_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_train_nameActionPerformed
        // TODO add your handling code here:
        String sourcevalue = setsource.getText();
        String destvalue = setdest.getText();
        String sname= "select distinct(tname) from train where (source_id=? and dest_id=?)";
        System.out.println(sourcevalue);
        System.out.println(destvalue);
               
       
        try
        {
            ps2=con.prepareStatement(sname);
            ps2.setString(1,sourcevalue);
            ps2.setString(2,destvalue);
            
            ResultSet rs=ps2.executeQuery();
            
            while(rs.next()){
                String ssname=rs.getString("tname");
                System.out.println(ssname);
                train_name.addItem(ssname);
                //System.out.println(ssname);
            }
            //Class.forName("")
            //Connection con= D
            //Statement stm= con.create                
            }
         catch(SQLException e){
             
             
                 
                 }
    }//GEN-LAST:event_train_nameActionPerformed

    private void class1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class1ActionPerformed
        // TODO add your handling code here:
        String s2name= "select distinct(class1) from train";
        
         try
        {
            ps2=con.prepareStatement(s2name);
            System.out.println("before ps2");
            ResultSet rs=ps2.executeQuery();
            System.out.println("after exec");
            
            while(rs.next()){
                String ss2name=rs.getString("class1");
                class1.addItem(ss2name);
            }
            
                        
            }
         catch(SQLException e){
                 
                 }
    }//GEN-LAST:event_class1ActionPerformed

    private void dodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dodActionPerformed

    private void nopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nopActionPerformed

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        // TODO add your handling code here:
        String selectednop=nop.getText();
        int n;
        n = Integer.parseInt(selectednop);
        int x=69;
        JOptionPane.showMessageDialog(null, "PNR NUMBER GENERATED:68923900"+x);
        for (int i = 0; i < n; i++) {
        JOptionPane.showMessageDialog(null, "PASSENGER ID GENERATED: " + "p00"+(i + 1));
        String storepid="p00"+(i+1);
                try{
        String sql1 = "insert into reservation values(?,?,?,?,?,?)";
        ps2 = con.prepareStatement(sql1);

//System.out.println(count);
//String genpid="p"+count;
//ps1.setString(1,"p"+count);
//pid.setText(genpid);
//System.out.println(genpid);
        ps2.setString(1,storepid);
        String sql2="select trainid from train where tname='?'";
            ps2=con.prepareStatement(sql2);
            //System.out.println("before ps2");
            ResultSet rs=ps2.executeQuery();
            String tnn=train_name.getSelectedItem().toString();
            
             ps2.setString(3,tnn);
            String cl=class1.getSelectedItem().toString();
            ps2.setString(4,cl);
            ps2.setString(5,"s"+i);
            
            
            
        
        ps2.setString(6,"6892390069"); 
            String dd=dod.getText().toString();
        ps2.setString(7,dd);
        ps2.execute();
        JOptionPane.showMessageDialog(this,"Inserted!");
        }
        catch(SQLException ex){
            Logger.getLogger(pas1.class.getName()).log(Level.SEVERE,null, ex);
           JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        
        
         //JFrame frame = new JFrame("Main Frame");
        //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //frame.setSize(400, 300);*/
                
        pass p=new pass();
        p.show();
        dispose();

            
        
        
        }
    }//GEN-LAST:event_proActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new res().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> class1;
    private javax.swing.JComboBox<String> destid;
    private javax.swing.JTextField dod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nop;
    private javax.swing.JButton pro;
    private javax.swing.JTextField setdest;
    private javax.swing.JTextField setsource;
    private javax.swing.JComboBox<String> sourceid;
    private javax.swing.JComboBox<String> train_name;
    // End of variables declaration//GEN-END:variables
}
